server:
  port: 8763

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaltZone: http://localhost:8761/eureka/

spring:
  application:
    name: service-client
  cloud:
    config:
      name: service-config #对应{application}部分
      profile: dev #对应{profile}部分
      label: master #对应git的分支。如果配置中心使用的是本地存储，则该参数无用
      discovery:
        enabled: true #开启Config服务发现支持
        service-id: config-server #指定配置中心的service-id，便于扩展为高可用配置集群。
  rabbitmq:
    host: localhost # 登录 Rabbitmq 后台管理页面地址为：http://localhost:15672
    port: 5672
    username: springcloud
    password: 123456

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    bus-refresh:
      enabled: true
    refresh:
      enabled: true