server:
  port: 8762

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaltZone: http://localhost:8761/eureka/

spring:
  application:
    name: service-client