server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaltZone: http://localhost:8761/eureka/

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cuizhongqiang/springCloud
          search-paths: config
  rabbitmq:
    host: localhost # 登录 Rabbitmq 后台管理页面地址为：http://localhost:15672
    port: 5672
    username: springcloud
    password: 123456

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    bus-refresh:
      enabled: true # /actuator/bus-refresh
    refresh:
      enabled: true # /actuator/refresh