server:
  port: 8886

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaltZone: http://localhost:8761/eureka/

spring:
  application:
    name: feign-server

feign:
  hystrix:
    enabled: true #启用断路器

management:
  endpoints:
    web:
      exposure:
        include: '*'
