server:
  port: 8887

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaltZone: http://localhost:8761/eureka/

spring:
  application:
    name: ribbon-server

management:
  endpoints:
    web:
      exposure:
        include: '*'